metricbeat.modules:
- module: system
  # to monitor container host, set --pid=host or --net=host when start this container
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 300
  processes: ['.*']
  cpu_ticks: false

- module: docker
  metricsets: ["cpu", "info", "memory", "network", "diskio", "container"]
  # map volume: -v "/var/run/docker.sock:/var/run/dockerhost/docker.sock"
  hosts: ["unix:///var/run/dockerhost/docker.sock"]
  enabled: true
  period: 300

output.logstash:
  enabled: true
  hosts: ["localhost:5044"]
  index: metricbeat
  
#output.elasticsearch:
#  hosts: ["localhost:9200"]
#  template.name: "metricbeat"
#  template.path: "metricbeat.template.json"
#  template.overwrite: false
